### ISSUE TITLE
(probably) matplotlib backend issue: saving plots on a remote machine not working correctly.

### ISSUE THREAD

**Issue by chan-y-park** [chan-y-park/loom#17]
From Pietro:
I have another question meanwhile, regarding saving plots: when I produce a set of plots by phase-scan,
and ask loom to save them through the .save() method of NetworkPlot, it will save the first one
in black/white for some reason, moreover the subsequent plots will be incredibly zoomed in, and nothing can be seen.

**Comment by plonghi** [comment]
The zooming can be corrected by manually specifying the kwarg 'plot_range', as you suggested, so not a big deal.

**Comment by neitzke** [comment]
What is the workaround? I ran into the same problem today.

**Comment by plonghi** [comment]
I don't encounter the problem anymore, by using the following commands:

c = loom.load_config(config_file)
d = loom.generate(c)
L = 4.0
snp = loom.plot(d, show_plot=False, plot_range=[[-L,L],[-L,L]])
snp.save(saving_folder_path, file_prefix=config_name+'_')

In this way I get color plots and everyone has the right plot range.
Did you already try this?

**Comment by neitzke** [comment]
Oh, I see -- no, I didn't try that, will try it and reopen if I still have a problem.
